### ISSUE TITLE
More information/'invalid class stanfit object'

### ISSUE THREAD

**Issue by jmannseth** [kaskr/tmbstan#1]
Hi,

Is there any way of retrieving the information obtained during the sampling  even if the following warning occurs:

'invalid class stanfit object: lp_ have undefined values'.

Or is it so that everything is atuomatically lost in this case?

Thank you!

Janne

**Comment by kaskr** [comment]
I haven't seen this error message before. Do have a simple
reproducible example ?

If the error message is triggered when *printing* the fitted object,
it may be that you can inspect the object manually. What does
`slotNames(fit)` give you ?

**Comment by jmannseth** [comment]
Hi,
my code right now is not very simple, but I will try to create an example and put it up here. 

The error message comes right after the following (n is number of samples):

Iteration: n/ n [100%]  (Sampling)
 Elapsed Time: 0.611284 seconds (Warm-up)
               0.656514 seconds (Sampling)
               1.2678 seconds (Total)

So it looks like any other try where everything runs fine, except for the error.
Also, when I have a very small amount of samples ( n < 30) no error occurs and everything seems normal. If I try, say, n = 100 the error occurs and of I try inspecting the object it doesn't exist (just like trying to print a value that is not defined yet). Therefore, I cannot use slotNames(fit), because it only says that 'fit' doesn't exist.

**Comment by kaskr** [comment]
It could be related to (lack of) numerical robustness of the specific
implementation.

The NUTS sampler sometimes runs *very* far out in the tails of the
distribution. The implemented likelihood function should handle these
extremes accurately - in particular not return `NaN` or `Inf`.

You can test robustness by evaluating `obj$fn` (or `obj$env$f` if
`random` is turned on ) at some extreme parameter values.

**Comment by colemonnahan** [comment]
I would not expect that to be the case. If you go out into the tails (which you will with a divergent transition) something will break down and you'll get a NaN or Inf, but Stan will convert that to infinite energy, 0 chance of accepting it, and thus never accept that point. So you're log-posterior should stay defined, even when this happens. tmbstan has always handled divergences just like Stan for me, meaning correctly.

I haven't seen this particular error either and am curious. Maybe if you start at an undefined place, by coincidence, it can never accept anything and then all of the log-posteriors are NaN? Do you start it from the MLE?
