### ISSUE TITLE
Missing forward method on TMB model

### ISSUE THREAD

**Issue by iagomosqueira** [kaskr/tmbstan#11]
Testing tmbstan on a TMB 2-stage fisheries model, in a package called 'bbm', still not out, and this error message pops up:

```
> fit <- tmbstan(model, chains=1)
Error in .local(object, ...) : 
  function 'tmb_forward' not provided by package 'bbm'
```

and it seems to relate to tmbstan/src/include/custom_func.hpp:29

```
tmb_forward = (FUN_PTR) R_GetCCallable(CHAR(STRING_ELT(dll_,0)), "tmb_forward");
```

I am a bit lost on where and how do tmb_forward and tmb_reverse get defined for a TMB model object. Is there anything that needs to be done in the call to MakeADFun()?

**Comment by kaskr** [comment]
There is some info [here](https://github.com/kaskr/adcomp/wiki/Development#distributing-code) about package development with TMB. Especially important is to have
```cpp
#define TMB_LIB_INIT R_init_mypkg
```
before
```cpp
#include <TMB.hpp>
```

**Comment by iagomosqueira** [comment]
Missed that. Working now. Thanks
