### ISSUE TITLE
Rich Hillary

### ISSUE THREAD

**Issue by ghost** [kaskr/tmbstan#12]
Hi

Having a problem with the initial values of the chain and those in the TMB object being passed to tmbstan not being the same - there so far away it's causing the NUTS sampler to start off in a basically impossible part of parameter space and the algorithm is struggling/failing even for a problem where the data are clearly very informative and the MLE estimates are all precise and clearly well defined. Using R 3.2.3 and TMB 1.7.14.

Here's the call to tmbstan

mcmc <- tmbstan(obj, init ='last.best.par' , iter = 100, chains=1,control=list(max_treedepth=12,adapt_delta=0.95))

and here's the comparison of what I thought should be the starting value and what I seem to have

> unlist(get_inits(mcmc))
        lnk       logl1       logl2       lncvl      lnmua1      lnmua2      lnmua3      lnmua4 
-0.37293663  0.51837301  0.54000729  1.32342703  0.42218097  1.54689306  1.63844182  1.55643495 
     lnmua5      lnmua6      lnmua7      lnmua8      lnmua9     lnmua10     lnmua11     lnmua12 
-0.25525449 -0.33151101 -1.69543298  1.83559237  1.11126283 -0.77444884  0.08670439  1.91483825 
    lnmua13     lnmua14     lnmua15     lnmua16     lnmua17     lnmua18      lnsda1      lnsda2 
 1.47439774  0.12719408  0.46998343 -0.88919106  0.29784446 -1.96843589 -1.71824515 -0.95844373 
     lnsda3      lnsda4      lnsda5      lnsda6      lnsda7      lnsda8      lnsda9     lnsda10 
 1.49492911  1.25991707  0.15519071 -0.35368503  1.36440148 -0.06872498 -0.05780251  0.74876643 
    lnsda11     lnsda12     lnsda13     lnsda14     lnsda15     lnsda16     lnsda17     lnsda18 
-1.00020935  1.14353937 -0.42968417  0.64377273 -0.95929183 -1.59583883  0.91959465 -0.02223809 

> obj$env$last.par.best
       lnk      logl1      logl2      lncvl      lnmua      lnmua      lnmua      lnmua      lnmua 
-3.0330080 -0.7103900  0.1531089 -1.9045480  2.0743056  1.7710718  1.8189095  1.9483136  1.7131364 
     lnmua      lnmua      lnmua      lnmua      lnmua      lnmua      lnmua      lnmua      lnmua 
 1.7758761  1.4500366  2.1507336  1.9298617  2.2874463  2.3909824  2.3530940  2.4673926  2.4899689 
     lnmua      lnmua      lnmua      lnmua      lnsda      lnsda      lnsda      lnsda      lnsda 
 2.4072272  2.3849279  2.4172995  2.3387358 -0.5842119 -0.9944923 -0.8474266 -0.4576827 -0.8598731 
     lnsda      lnsda      lnsda      lnsda      lnsda      lnsda      lnsda      lnsda      lnsda 
-1.1812362 -0.8252914 -1.0972448 -0.9424892 -0.8304834 -0.8302608 -0.8722572 -1.0873038 -0.6452459 
     lnsda      lnsda      lnsda      lnsda 
-0.8172137 -0.7002530 -0.6932244 -0.6358614 

Just wondering if you can see if i'm doing anything demonstrably wrong as these two should match up but don't, and given the starting values i'm not surprised I cannot get the NUTS algorithm going. Any advice or tips gratefully received!

Thanks
Rich Hillary

**Comment by ghost** [comment]
Sorry I have the wrong call in there to tmbstan the actual call is I think correct:

cmc <- tmbstan(obj, init ='last.par.best' , iter = 100, chains=1,control=list(max_treedepth=12,adapt_delta=0.95))

but I still get the same issue. I also get the same issue using the init = 'par' option where obj$env$par and the initial values aren't even close

Cheers
Rich H

**Comment by kaskr** [comment]
I cannot reproduce the problem. This looks good to me:

```R
library(tmbstan)
example(tmbstan)
mcmc <- tmbstan(obj, init ='last.par.best', iter = 100, chains=1, control=list(max_treedepth=12, adapt_delta=0.95))
plot(unlist(get_inits(mcmc)), obj$env$last.par.best )
abline(0, 1)
```

Please post a full reproducible example.

Note that `last.par.best` is dynamic, i.e. it might change whenever you evaluate `obj$fn`. That could in principle explain the difference.

**Comment by ghost** [comment]
Hi 

I version-solved the issue as it goes away basically with R 3.5.1, TMB 1.7.15 and tmbstan 1.0.1. I can still send you the example that doesn't run if you want to just to see if I was causing the problem or there is some kind of weird bug but only if you need it. With these versions the NUTS algo is mixing nicely and producing the kind of samples I would expect given the MLE estimates and covariances

Cheers
Rich
