### ISSUE TITLE
Example of `tmbstan` crashes my R session

### ISSUE THREAD

**Issue by guilhermeparreira** [kaskr/tmbstan#15]
Hi there! 

When I run the first example of `tmbstan::tmbstan`, it crashes my R session.

Code:

```
library(tmbstan)
rstan_options(auto_write = T)
options(mc.cores = parallel::detectCores())
runExample("simple")
fit <- tmbstan(obj, chains=1) # Crashes
```

Example:
![tmbstan](https://user-images.githubusercontent.com/13880005/81109255-332b6a80-8ef0-11ea-9049-676238fd7222.png)

When I run via terminal I get:

```
SAMPLING FOR MODEL 'tmb_generic' NOW (CHAIN 1).
double free or corruption (out)
Aborted (core dumped)
```

Why is that? (I know that it is not an Issue, but I think that it is best channel to chat).
I have just installed `tmbstan` package from github

**Comment by kaskr** [comment]
I cannot reproduce the problem. First thing to check is that you don't have anything non-standard in `~/.R/Makevars` that could cause illegal optimizations by the compiler. (e.g `-O3` see
https://github.com/glmmTMB/glmmTMB/issues/297)

**Comment by guilhermeparreira** [comment]
This is what I have initially in the file `~/.R/Makevars`:
```
CXX14FLAGS=-O3 -march=native -mtune=native -fPIC
CXX14=g++
```
Then I added `CXXFLAGS=-O0 -g` to the file `~/.R/Makevars` and re-install `tmbstan`. After that, I started R from command line using `R -d gdb` + `run` + `library(tmbstan)` + `runExample("simple")` + `fit <- tmbstan(obj, chains=1)` and I got:

```
> fit <- tmbstan(obj, chains=1)
SAMPLING FOR MODEL 'tmb_generic' NOW (CHAIN 1).
double free or corruption (out)
Program received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) 
```

**Comment by kaskr** [comment]
The simple example must be rebuilt:
```r
runExample("simple", clean=TRUE)
```

**Comment by kaskr** [comment]
From (gdb) please do 'bt' + enter.

**Comment by guilhermeparreira** [comment]
Sorry @kaskr , I quite didn't understand. But what I did was:

`R -d gdb` + `run` + `library(tmbstan)` + `runExample("simple", clean = T)` + `'bt'`

and I got:

![image](https://user-images.githubusercontent.com/13880005/81175842-995ccf80-8f7a-11ea-9e93-b4b892f2d9f9.png)

**Comment by kaskr** [comment]
'bt' is debugger command - not an R command...
But never mind, I managed to reproduce the crash using your `~/.R/Makevars`.
**Solution**: Get rid of that file, at least temporarily, while re-installing tmbstan. Keep an eye on the compilation to make sure that `-O3 -march=native -mtune=native` doesn't appear. Please confirm that it works - thanks!

**Comment by guilhermeparreira** [comment]
A, I understand now =) sorry. When I did  `bt` from gdb resulted `No stack`.
I will do it right now

**Comment by guilhermeparreira** [comment]
I deleted the `~/.R/Makevars` file, re-installed `tmbstan` and no `-O3 -march=native -mtune=native` appeared. And yes, it worked!! Thanks kaskr!!

Should I create the `~/.R/Makevars` file again? (With which content?)
Thank you again!

**Comment by kaskr** [comment]
I guess you can restore your old Makevars if you are willing to sacrifice accuracy and stability for a little extra speed. At least now you know the risk.

**Comment by guilhermeparreira** [comment]
Ok! Thank you!!
