### ISSUE TITLE
Compile errors after loading tmbstan/rstan

### ISSUE THREAD

**Issue by Cole-Monnahan-NOAA** [kaskr/tmbstan#16]
I am unable to recompile a TMB model after loading tmbstan. I've talked to other uses with a similar situation. I assume this must be related to how `rstan` is configured since it is trying to pull in StanHeader libraries? Any advice on how to resolve this?

My makevars is below, where I did not follow the rstan configuration based on a previous conversation with @kaskr (admittedly a long time ago). 

````
CFLAGS = -O2 $(DEBUGFLAG) -std=gnu99 -mtune=core2
CXXFLAGS = -O2 $(DEBUGFLAG) -mtune=core2
CXX1XFLAGS = -O2 $(DEBUGFLAG) -mtune=core2
PKG_CPPFLAGS += -DSUPPORT_OPENMP

CXXFLAGS=-O3 -Wno-unused-variable -Wno-unused-function
````

Reproducible example:
````
library(TMB)
runExample('simple', clean=TRUE)

Building example simple 
Note: Using Makevars in C:/Users/cole.monnahan/emacs-lisp/.R/Makevars 
C:/Rtools/mingw_64/bin/g++ -std=gnu++11  -I"C:/PROGRA~1/R/R-36~1.3/include" -DNDEBUG -IC:/Users/COLE~1.MON/RLibs/TMB/include -IC:/Users/COLE~1.MON/RLibs/RCPPEI~1/include  -DTMB_SAFEBOUNDS -DLIB_UNLOAD=R_unload_simple  -DTMB_LIB_INIT=R_init_simple          -O3 -Wno-unused-variable -Wno-unused-function -c simple.cpp -o simple.o
C:/Rtools/mingw_64/bin/g++ -std=gnu++11 -shared -s -static-libgcc -o simple.dll tmp.def simple.o -LC:/PROGRA~1/R/R-36~1.3/bin/x64 -lR
Build time 23.2 seconds
````

Now if I load rstan it fails:

````
library(tmbstan)
runExample('simple', clean=TRUE)

Cleanup:
Building example simple 
Note: Using Makevars in C:/Users/cole.monnahan/emacs-lisp/.R/Makevars 
C:/Rtools/mingw_64/bin/g++ -std=gnu++11  -I"C:/PROGRA~1/R/R-36~1.3/include" -DNDEBUG -IC:/Users/COLE~1.MON/RLibs/TMB/include -IC:/Users/COLE~1.MON/RLibs/RCPPEI~1/include  -DTMB_SAFEBOUNDS -DLIB_UNLOAD=R_unload_simple  -DTMB_LIB_INIT=R_init_simple        -include C:/Users/cole.monnahan/RLibs/StanHeaders/include/stan/math/prim/mat/fun/Eigen.hpp -I "C:/Users/cole.monnahan/RLibs/StanHeaders/include" -I "C:/Users/cole.monnahan/RLibs/RcppEigen/include"   -O3 -Wno-unused-variable -Wno-unused-function -c simple.cpp -o simple.o
In file included from C:/Users/COLE~1.MON/RLibs/TMB/include/cppad/local/testvector.hpp:104:0,
                 from C:/Users/COLE~1.MON/RLibs/TMB/include/cppad/cppad.hpp:67,
                 from C:/Users/COLE~1.MON/RLibs/TMB/include/TMB.hpp:62,
                 from simple.cpp:2:
C:/Users/COLE~1.MON/RLibs/TMB/include/cppad/example/cppad_eigen.hpp:72:0: warning: "EIGEN_MATRIXBASE_PLUGIN" redefined
 # define EIGEN_MATRIXBASE_PLUGIN <cppad/example/eigen_plugin.hpp>
 ^
In file included from <command-line>:0:0:
C:/Users/cole.monnahan/RLibs/StanHeaders/include/stan/math/prim/mat/fun/Eigen.hpp:10:0: note: this is the location of the previous definition
 #define EIGEN_MATRIXBASE_PLUGIN "stan/math/prim/mat/eigen_plugins.h"
 ^
In file included from C:/Users/COLE~1.MON/RLibs/RCPPEI~1/include/Eigen/src/Core/MatrixBase.h:130:0,
                 from C:/Users/COLE~1.MON/RLibs/RCPPEI~1/include/Eigen/Core:436,
                 from C:/Users/COLE~1.MON/RLibs/RCPPEI~1/include/Eigen/Dense:1,
                 from C:/Users/cole.monnahan/RLibs/StanHeaders/include/stan/math/prim/mat/fun/Eigen.hpp:13,
                 from <command-line>:0:
C:/Users/cole.monnahan/RLibs/StanHeaders/include/stan/math/prim/mat/eigen_plugins.h:22:30: error: 'conditional_t' in namespace 'std' does not name a template type
 using double_return_t = std::conditional_t<std::is_const<std::remove_reference_t<T>>::value,

[truncated]

make: *** [C:/PROGRA~1/R/R-36~1.3/etc/x64/Makeconf:215: simple.o] Error 1
Error in compile(paste0(name, ".cpp"), ...) : Compilation failed
In addition: Warning message:
In file.remove(paste0(name, ".o")) :
  cannot remove file 'simple.o', reason 'No such file or directory'
Timing stopped at: 0.01 0.04 5.25
````

`sessionInfo()`
````
R version 3.6.3 (2020-02-29)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19041)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] tmbstan_1.0.2        rstan_2.19.3         ggplot2_3.3.2       
[4] StanHeaders_2.21.0-5 TMB_1.7.16          

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.4.6       pillar_1.4.4       compiler_3.6.3     prettyunits_1.1.1 
 [5] tools_3.6.3        packrat_0.5.0      pkgbuild_1.0.8     lifecycle_0.2.0   
 [9] tibble_3.0.1       gtable_0.3.0       lattice_0.20-38    pkgconfig_2.0.3   
[13] rlang_0.4.6        Matrix_1.2-18      cli_2.0.2          rstudioapi_0.11   
[17] parallel_3.6.3     loo_2.2.0          gridExtra_2.3      withr_2.2.0       
[21] dplyr_1.0.0        generics_0.0.2     vctrs_0.3.1        stats4_3.6.3      
[25] grid_3.6.3         tidyselect_1.1.0   glue_1.4.1         inline_0.3.15     
[29] R6_2.4.1           processx_3.4.2     fansi_0.4.1        purrr_0.3.4       
[33] callr_3.4.3        magrittr_1.5       codetools_0.2-16   matrixStats_0.56.0
[37] scales_1.1.1       ps_1.3.3           ellipsis_0.3.1     assertthat_0.2.1  
[41] colorspace_1.4-1   RcppParallel_5.0.2 munsell_0.5.0      crayon_1.3.4 
````

**Comment by kaskr** [comment]
@Cole-Monnahan-NOAA  I cannot reproduce. Please confirm you are restarting R for each try.

From a *clean R session* I'm running your chunk (**A**) but it works for me without problems:

```r
library(TMB)
runExample('simple', clean=TRUE)
library(tmbstan)
runExample('simple', clean=TRUE)
```

From a *clean R session* the following chunk (**B**) doesn't work for me

```r
library(TMB)
runExample('simple')
library(tmbstan)
fit <- tmbstan(obj, chains=1)
runExample('simple')
```

I get

> > dyn.load(dynlib("simple"))
> Warning: 4 external pointers will be removed
> Error in dyn.load(dynlib("simple")) : 
>   Failed to clean. Please manually clean up before unloading


**Update**
I'm just spotting something odd though: Comparing the compilation output between your two `runExample` it seems that `library(tmbstan)` added stuff to the compiler behind your back:
```shell
-include C:/Users/cole.monnahan/RLibs/StanHeaders/include/stan/math/prim/mat/fun/Eigen.hpp -I "C:/Users/cole.monnahan/RLibs/StanHeaders/include" -I "C:/Users/cole.monnahan/RLibs/RcppEigen/include"
```

**Comment by Cole-Monnahan-NOAA** [comment]
@kaskr yes it works if I restart R. But I would like to avoid restarting R every time I need to compile the model. Can you do it without restarting?

That's what I meant by "I assume this must be related to how rstan is configured since it is trying to pull in StanHeader libraries?" It's looking in the wrong place for Eigen. 

Does that happen to you too, but you can compile fine regardless?

Before loading any libraries "compile" is found in one place: namespace:compiler. After loading TMB I get:

````
> getAnywhere('compile')
2 differing objects matching ‘compile’ were found
in the following places
  package:TMB
  namespace:compiler
  namespace:TMB
````

Then if I load tmbstan I get an additional one:

````
> getAnywhere('compile')
3 differing objects matching ‘compile’ were found
in the following places
  package:TMB
  namespace:compiler
  namespace:TMB
  namespace:generics 
````

My issue is not resolved by using `TMB::compile` either.

**Comment by kaskr** [comment]
@Cole-Monnahan-NOAA 
> But I would like to avoid restarting R every time

Yes - it's just to make sure that the problem you report is actually in chunk **A** and not a derived effect of something else.

> Can you do it without restarting?

I seem to be able to run chunk **A** many times without restarting. And my compiler outputs are the same each time even after loading tmbstan.

> Before loading any libraries "compile" is found in one place: namespace:compiler. After loading TMB I get:

OK - doesn't seem to be a problem.

I notice that you get the same message from `TMB::compile` each time:
```
Note: Using Makevars in C:/Users/cole.monnahan/emacs-lisp/.R/Makevars
```
This is where the compiler flags and paths are picked up by `TMB::compile`. Did the file by any chance change after loading tmbstan?

You should be able to `debug(TMB::compile)` and track how it sets the flags. It creates a temporary file `mvfile`, which is deleted on exit, but while debugging you can check its content and ultimately figure out where the weird stuff come from.

**Comment by Cole-Monnahan-NOAA** [comment]
Here is Makevars before loading `tmbstan`:
````
CFLAGS = -O2 $(DEBUGFLAG) -std=gnu99 -mtune=core2
CXXFLAGS = -O2 $(DEBUGFLAG) -mtune=core2
CXX1XFLAGS = -O2 $(DEBUGFLAG) -mtune=core2
PKG_CPPFLAGS += -DSUPPORT_OPENMP

CXXFLAGS=-O3 -Wno-unused-variable -Wno-unused-function
````
Then with that debug trick when I look at the `mvfile` it adds this line:

````
PKG_CPPFLAGS=-IC:/Users/COLE~1.MON/RLibs/TMB/include -IC:/Users/COLE~1.MON/RLibs/RCPPEI~1/include  -DTMB_SAFEBOUNDS -DLIB_UNLOAD=R_unload_simple  -DTMB_LIB_INIT=R_init_simple 
````

**Comment by kaskr** [comment]
@Cole-Monnahan-NOAA 
That looks normal (it is part of your compiler output in both cases).
No trace of
```
-include C:/Users/cole.monnahan/RLibs/StanHeaders/include/stan/math/prim/mat/fun/Eigen.hpp -I "C:/Users/cole.monnahan/RLibs/StanHeaders/include" -I "C:/Users/cole.monnahan/RLibs/RcppEigen/include"
```
anywhere?
If it's not in `mvfile` then it must be in some environment variable set by someone somewhere... I'm out of clues.

**Comment by Cole-Monnahan-NOAA** [comment]
OK it is definitely `StanHeaders`. If I load that after TMB, but not rstan/tmbstan then it still happens.

This package is very limited in dox but the one help page they have is for an unexported function `?StanHeaders::CxxFlags` that says this:

````
These functions are currently not exported and are typically called from a Makevars or a Makevars.win file of another package as follows:

PKG_CXXFLAGS += $(shell "$R_HOME/bin/Rscript" -e "StanHeaders:::CxxFlags()") 
PKG_LDLIBS += $(shell "$R_HOME/bin/Rscript" -e "StanHeaders:::LdFlags()")
````

So this package must be messing with my environmental variables. I will create an issue with `StanHeaders` and update this when resolved.

**Comment by Cole-Monnahan-NOAA** [comment]
Two quick updates. This is new behavior in StanHeaders. So you can avoid it by reverting back to an older version of the package like, e.g.,

````
devtools::install_version("StanHeaders", version = "2.19.0", repos = "http://cran.us.r-project.org")
````
I have an open issue with `rstan` so we'll see what they say.

Second, and unrelated maybe, is that when the simple example files to compile when using `runExample` like above, then the next time I start an R session and call `library(TMB)` it automatically recompiles the file (below). That is very unexpected... is it normal? I have never seen that before. It does not do that if the simple example was successfully run.

````
> library(VAST)
Loading required package: TMB
Building example simple 
Note: Using Makevars in C:\Users\cole.monnahan\emacs-lisp/.R/Makevars 
C:/Rtools/mingw_64/bin/g++ -std=gnu++11  -I"c:/PROGRA~1/R/R-36~1.3/include" -DNDEBUG -IC:/Users/COLE~1.MON/RLibs/TMB/include -IC:/Users/COLE~1.MON/RLibs/RCPPEI~1/include  -DTMB_SAFEBOUNDS -DLIB_UNLOAD=R_unload_simple  -DTMB_LIB_INIT=R_init_simple          -O3 -Wno-unused-variable -Wno-unused-function -c simple.cpp -o simple.o
C:/Rtools/mingw_64/bin/g++ -std=gnu++11 -shared -s -static-libgcc -o simple.dll tmp.def simple.o -Lc:/PROGRA~1/R/R-36~1.3/bin/x64 -lR
Build time 25.08 seconds
````

**Comment by kaskr** [comment]
> That is very unexpected... is it normal?

Yes, it's a kludge to satisfy a CRAN policy. Examples are only allowed to run 5 seconds,  so `library(TMB)` triggers build of the simple example if it doesn't exist, effectively moving the `25.08 seconds` from example time to install time.

**Comment by Cole-Monnahan-NOAA** [comment]
This was an issue with StanHeaders and has been resolved per this issue:

https://github.com/stan-dev/rstan/issues/786

The solution for `tmbstan` users is to simply update the package `StanHeaders` from CRAN.
