### ISSUE TITLE
How to produce the random effects estimates when using laplace=TRUE in tmbstan?

### ISSUE THREAD

**Issue by catarinawor** [kaskr/tmbstan#26]
Is there a way of extracting the "posterior estimates" when the laplace approximation is used in TMBstan?

I know that the laplace approximation values will not be produced with the `obj$report()` function but is there an efficient way of extracting these values given each row of the posterior estimates for the fixed parameters?

**Comment by kaskr** [comment]
A bit late - sorry, I hadn't seen this. Something like

```r
f <- function(par) {
  obj$fn(par) ## Update inner parameters
  obj$env$last.par[obj$env$random]
}
```

applied to each MCMC sample of outer parameters.

Given that these have already been calculated *during MCMC* it would in principle have been more efficient to extract them there. But that option is not available in tmbstan.
