### ISSUE TITLE
Extract Stan code?

### ISSUE THREAD

**Issue by jebyrnes** [kaskr/tmbstan#28]
I’m trying to compare how glmmtmb objects are turned into Stan objects with tombs tan versus objects from rethinking and brms. Is there an easy way to extract the stan code for tmbstan objects?

**Comment by kaskr** [comment]
tmbstan doesn't use stan code, so no.

**Comment by jebyrnes** [comment]
Ah, my bad! I thought it did! That would explain why poking through the entire fit object structure I didn't find it. HA! I'm working on trying to make a comparison between glmmTMB with tmbstan and brms for identical models, so, trying to dig into the guts of things. If you have any pointers, would be much appreciated!
