### ISSUE TITLE
How to build a TMB model object?

### ISSUE THREAD

**Issue by yashreem** [kaskr/tmbstan#7]
I want to execute MCMC sampling using MLE estimates as initial values for the chains. I am trying to use tmbstan but I am unable to figure out the exact path of using this package. It would be helpful if you can let me know the steps (specifically, the tmb model object) and the overall procedure.

Thank you.

**Comment by kaskr** [comment]
@yashreem 

To use the tmbstan package you'll have to be familiar with TMB. Here's a  brief [tutorial](https://github.com/kaskr/adcomp/wiki/Tutorial) on how to create a TMB model object. See also the [TMB wiki](https://github.com/kaskr/adcomp/wiki) for the available documentation.

Being familiar with TMB, the overall procedure on how to run MCMC should be clear from the tmbstan [main page](https://github.com/kaskr/tmbstan#examples).
